apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanagerapp
spec:
  selector:
    matchLabels:
      app: stockmanagerapp
  replicas: 1
  template:
    metadata:
      labels:
        app: stockmanagerapp
    spec:
      containers:
      - name: stockmanagerapp
        image: gerryik/stockmanager:latest
        ports:
        - containerPort: 8030
