apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
spec:
  selector:
    matchLabels:
      app: stockmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
      - name: stockmanager
        image: gerryik/stockmanager:latest
        ports:
        - containerPort: 8030
